version: "3.9"

services:
        app:
                container_name: aml-pos-service
                build:
                        context: .
                        dockerfile: Dockerfile
                volumes:
                        - ./:/var/www
                ports:
                        - "9100:9100"
                working_dir: /var/www
                command: /bin/sh -c "uvicorn main:app --host=0.0.0.0 --port=9100 --reload"

networks:
        default:
                name: iu-network
